### ISSUE TITLE
Adding new pokemon in main.py (help)

### ISSUE THREAD

**Issue by importhuman** [Sahil-k1509/cmd_pokemon#13]
I tried the following before main_menu in main.py:
```python
zapdosData = pokemonWorld['zapdos']
Zapdos = Pokemon('zapdos', zapdosData, 0)
Zapdos.npcPokemonReady(100)
```

But I cannot figure out how to add the pokemon to the player. I've tried append methods with player and pokemonTrainer, but the methods I try do not seem to work. Please help. I've tried with deepcopy in the first line as well, I think I'm just missing the command to add the pokemon to the player.

**Comment by Sahil-k1509** [comment]
I used 
```
zapdosData =  deepcopy(pokemonWorld['zapdos'])
Zapdos = Pokemon('zapdos', zapdosData, 0)
Zapdos.npcPokemonReady(100)
player.pokemonInHand.append(Zapdos)
```
(after line 141 where pprint('welcome back') is there.)
And it works perfectly(just make sure you import deepcopy[Or from copy import deepcopy will do. it's an inbuilt module too] from npc.py and pokemonworld from pokeworld.py). I am able to use this level 100 Zapdos for duelling.
But you should only append in the `pokemonInHand` list only when there are less than 7 pokemons in list already. otherwise use player.archivePokemons.append(Zapdos) and then you can visit pokemon centre in game to switch pokemon from hand to archive.

**Comment by importhuman** [comment]
It works now, thanks! I was doing it outside the loop, so I kept getting errors. 

I had this in my other doubts, but since it has come up I'll ask it now. Why do we need deepcopy? I tried it without deepcopy as well and it still works.

**Comment by Sahil-k1509** [comment]
They are all dictionaries that store the data of pokemon and by default Dictionaries(even arrays Or custom objects) are passed by reference, so if you change any data from one variable. It will change in all the variables that point to same object. E.g. if in fight opponent used tackle. The code will reduce pp of tackle from your pokemon too which is problematic. So to avoid that i used deepcopy. In pokemon world when I'm assigning attacks to pokemons. I have created my own deepcopy to copy the Attack object because inbuilt deepcopy doesn't work for custom classes.

**Comment by importhuman** [comment]
Is there a similar way to remove pokemon? I realized that since the game saved after adding, I can't remove the added pokemon from the game by simply modifying the code in main.py.
