### ISSUE TITLE
Pokemon.py attack() bugs

### ISSUE THREAD

**Issue by importhuman** [Sahil-k1509/cmd_pokemon#14]
Saw this bit:
```python
elif enemyType in typeDisadantages[attackType]:
	pprint("It's not very effective !!")
	sleep(0.2)
	enemyPokemon.health += floor((0.2+random()*0.5)*attackUsed.damage)
```

Is the += a typo or deliberate healing?
Also,
```python
if attackUsed.recoil != 0:
	sleep(0.2)
	pprint(f"{self.name} got a recoil of {-floor(attackUsed.recoil)}"); sleep(0.2)
	self.health += floor(attackUsed.recoil)
	self.health = max(0, self.health)
```

Here also recoil is leading to healing. This is also a bug?

**Comment by Sahil-k1509** [comment]
This is deliberate. If we are in disadvantage by type we won't deal a lot of damage to opponent. So I made the opponent gain 20-70% of health caused by attack and reduced health by total damage. Overall our attack will do 30-80% damage. I used this way of doing it because I anyway had to reduce total damage for all cases. 

In second code. Recoil isn't leading to heal. The actual value of recoil is negative. So adding it will decrease health. See above. I have printed "-attackUsed.recoil". That negative signs cancels original negative sign so prints something like " You received a recoil of 20hp"

**Comment by importhuman** [comment]
> I made the opponent gain 20-70% of health caused by attack and reduced health by total damage. 

Is this why there are 2 damage calculations in the loop, one for type effectiveness and one that is applied in all cases?

> In second code. Recoil isn't leading to heal. The actual value of recoil is negative. So adding it will decrease health. See above. I have printed "-attackUsed.recoil". That negative signs cancels original negative sign so prints something like " You received a recoil of 20hp"

Yes but original recoil has been input as positive values in all attacks in attacklist.py, so print message will be -20 hp but it will actually increase HP.

**Comment by Sahil-k1509** [comment]
> Yes but original recoil has been input as positive values in all attacks in attacklist.py, so print message will be -20 hp but it will actually increase HP.
Check out attack.py, I have done self.recoil = -recoil (recoil is the value we are passing in attacklist.py). I know it doesnt make much sense(Now even I don't remember why I thought of giving a negative sign after taking positive value)

**Comment by importhuman** [comment]
Oh right, all good then.

> Is this why there are 2 damage calculations in the loop, one for type effectiveness and one that is applied in all cases?

What about the 2 damage calculations?

**Comment by Sahil-k1509** [comment]
Yes inside if else conditions, health is reduced or gained for special cases like critical hit, effective and non effective hits. And outside conditions is the default/Common health decrease for all cases(above three and just normal attack)
